### ISSUE TITLE
JSMin Incorrectly Parses Javascript

### ISSUE THREAD

**Issue by chrisspen** [mintchaos/django_compressor#53] opened 2010-12-21 17:24 UTC
JSMin chokes on the script jquery.select_skin.js, available from http://www.verot.net/jquery_select_skin.htm. It's a relatively simple script, and shouldn't present any problem for JSMin. Yet if I do:

```
{% compress js %}
<script type="text/javascript" src="js/jquery.select_skin.js"></script>
{% endcompress %}
```

then the compressor fails silently and outputs no minimized file. If I gut the jquery.select_skin.js file, then the compressor outputs a file.

**Comment by chrisspen** [comment] 2010-12-21 17:31
Since it looks like jsmin.py has been unmaintained for years, is it possible to plug in a different JSMin implementation into django_compressor?

**Comment by chrisspen** [comment] 2010-12-21 17:51
On second look, it looks like the issue is caused by the file jquery.formset.js I'm including right before jquery.select_skin.js. Specifically, the part of the file that's breaking JSMin is the end:

```
})(jQuery)
```

Adding a ";" to the end works around the bug in JSMin. Even without the trailing semi-colon, it's still valid Javascript, and should be handled correctly by JSMin.

**Comment by jezdez** [comment] 2011-02-16 14:09
I can't reproduce it neither with jquery.select_skin.js nor with jquery.formset.js (from http://code.google.com/p/django-dynamic-formset/). Would you mind posting the actual error message or traceback?

**Comment by jezdez** [comment] 2011-04-12 09:31
Closing as worksforme, please reopen at the new home http://github.com/jezdez/django_compressor

**Closed as completed by jezdez** 2011-04-12 09:31 UTC
